[package]
name = "parse-algorithms"
version = "0.1.0"
authors = ["Dzenan Jupic <info@dzenanjupic.de>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
syn = "1.0.19"
quote = "1.0.4"
proc-macro2 = "1.0.12"
