[package]
name = "template-algorithm"
version = "0.1.0"
authors = ["Dzenan Jupic <info@dzenanjupic.de>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]


[dependencies]
algorithm-utils = {path="../../algorithm-utils"}
